In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn import linear_model
from sklearn.metrics import r2_score

In [5]:
df = pd.read_csv(r"C:\Users\ishit\Downloads\fantasyPL.csv")
df.fillna(0,inplace=True)
df

,now_cost,position,transfers_in_event,influence_rank_type,ict_index_rank_type,assists,selected_rank,direct_freekicks_order,starts_per_90,goals_conceded,...,now_cost_rank_type,ict_index,now_cost_rank,minutes,yellow_cards,cost_change_event_fall,red_cards,value_form,ict_index_rank,total_points
0,44,FWD,0,61,63,0,325,0.0,0.00,0,...,94,0.0,528,0,0,0,0,0.0,628,0
1,39,DEF,433,173,172,0,253,0.0,0.00,0,...,231,0.0,729,0,0,0,0,0.0,493,0
2,44,MID,54,215,214,1,438,0.0,0.00,0,...,290,0.4,498,1,0,0,0,0.0,470,4
3,54,MID,5,134,139,3,430,0.0,0.76,2,...,80,21.9,127,236,0,0,1,0.0,300,21
4,49,DEF,104278,42,47,0,21,0.0,0.98,13,...,31,43.3,247,1284,1,0,0,0.9,172,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
764,45,MID,13,269,272,0,746,0.0,0.00,0,...,250,0.0,428,0,0,0,0,0.0,680,0
765,45,MID,20,277,280,0,733,0.0,0.00,0,...,258,0.0,441,0,0,0,0,0.0,693,0
766,40,DEF,151,217,217,0,624,0.0,0.00,0,...,211,0.0,703,0,0,0,0,0.0,579,0
767,45,MID,11,257,260,0,769,0.0,0.00,0,...,232,0.0,401,0,0,0,0,0.0,663,0
768,45,MID,24,271,274,0,764,0.0,0.00,0,...,252,0.0,431,0,0,0,0,0.0,683,0

In [6]:
df.shape

(769, 72)

In [7]:
df.isna().sum()

now_cost                  0
position                  0
transfers_in_event        0
influence_rank_type       0
ict_index_rank_type       0
                         ..
cost_change_event_fall    0
red_cards                 0
value_form                0
ict_index_rank            0
total_points              0
Length: 72, dtype: int64

In [9]:
le_pos = preprocessing.LabelEncoder()
df['position'] = le_pos.fit_transform(df['position'])
le_dreamteam = preprocessing.LabelEncoder()
df['in_dreamteam'] = le_dreamteam.fit_transform(df['in_dreamteam'])
#model 1
#print("\nMODEL 1\n")
X = df.drop(['now_cost'],axis=1)
y = df[['now_cost']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)
regr = linear_model.LinearRegression()
regr.fit(X_train, y_train)
y_hat = regr.predict(X_test)
print("Mean Squared Error (MSE) : %.2f" % np.mean((y_hat - y_test) ** 2))
print('Variance score: %.2f' % regr.score(X_test, y_test))
print('R2 Score', r2_score(y_test, y_hat))
print ('Intercept: ',regr.intercept_)
#print ('Coefficients: ', regr.coef_)

Mean Squared Error (MSE) : 40.34
Variance score: 0.66
R2 Score 0.6557536049671742
Intercept:  [46.96426055]